WebApp.NET_MVC-2022-12D-PP_Encuestadora/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.NET_MVC_2022_12D_PP_Encuestadora.Context;
using WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models;

namespace WebApp.NET_MVC_2022_12D_PP_Encuestadora.Controllers
{
    public class ClienteController : Controller
    {
        private readonly EncuestadoraDBContext _context;

        public ClienteController(EncuestadoraDBContext context)
        {
            _context = context;
        }

        // GET: Cliente Asynchronous EF methods in ASP.NET Core web apps
        //https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-6.0&tabs=visual-studio#asynchronous-ef-methods-in-aspnet-core-web-apps
        public async Task<IActionResult> Index()
        {
            return View(await _context.clientes.ToListAsync());
        }

        // GET: Cliente/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.clientes
                .Include(s => s.encuestas)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ClienteId == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Cliente/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cliente/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClienteId,nombreCliente,mailCliente,passwordCliente,empresaCliente,cuitCliente,domicilioCliente,precioCliente")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Cliente/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Cliente/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClienteId,nombreCliente,mailCliente,passwordCliente,empresaCliente,cuitCliente,domicilioCliente,precioCliente")] Cliente cliente)
        {
            if (id != cliente.ClienteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.ClienteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Cliente/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.clientes
                .FirstOrDefaultAsync(m => m.ClienteId == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Cliente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.clientes.FindAsync(id);
            _context.clientes.Remove(cliente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            return _context.clientes.Any(e => e.ClienteId == id);
        }
    }
}

WebApp.NET_MVC-2022-12D-PP_Encuestadora/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models;

namespace WebApp.NET_MVC_2022_12D_PP_Encuestadora.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }
        public IActionResult Faqs()
        {
            return View();
        }

        public IActionResult LogIn()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp.NET_MVC-2022-12D-PP_Encuestadora/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.NET_MVC_2022_12D_PP_Encuestadora.Context;
using WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models;

namespace WebApp.NET_MVC_2022_12D_PP_Encuestadora.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly EncuestadoraDBContext _context;

        public UsuarioController(EncuestadoraDBContext context)
        {
            _context = context;
        }

        // GET: Usuario
        public async Task<IActionResult> Index()
        {
            return View(await _context.usuarios.ToListAsync());
        }

        // GET: Usuario/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.usuarios
                .FirstOrDefaultAsync(m => m.UsuarioId == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        public async Task<IActionResult> PuntosAcumulados(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.usuarios
                .FirstOrDefaultAsync(m => m.UsuarioId == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuario/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuario/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UsuarioId,nombreUsuario,mailUsuario,passwordUsuario,dniUsuario,datetimeFechaNacimiento,domicilioUsuario,preferenciaUsuario")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuario/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuario/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UsuarioId,nombreUsuario,mailUsuario,passwordUsuario,dniUsuario,datetimeFechaNacimiento,domicilioUsuario,preferenciaUsuario")] Usuario usuario)
        {
            if (id != usuario.UsuarioId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.UsuarioId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuario/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.usuarios
                .FirstOrDefaultAsync(m => m.UsuarioId == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.usuarios.FindAsync(id);
            _context.usuarios.Remove(usuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.usuarios.Any(e => e.UsuarioId == id);
        }
    }
}

WebApp.NET_MVC-2022-12D-PP_Encuestadora/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About Page";
}

<div>
    @*<p>--------------------Seccion About--------------------</p>*@
    @*<p><a class="text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Index Clientes</a></p>
        <p>Comentario1: Falta filtrar encuestas solo creadas por el cliente</p>*@
<div class="content bg-white">
    <div class="content container-fluid">
        <section class="row">
            <div class="col-12 col-lg-6">
                <div style="margin:23px 0;">
                    <h1>
                        Sobre nosotros
                    </h1>
                </div>
                <div class="section-text">
                    El objetivo de La Encuestadora es ofrecerle las encuestas que mejor pagan en Internet.
                </div>
                <div class="text-center">
                    <a class="start-here-button d-inline-block" href="/Home/LogIn">
                        ¿Quiere unirse? haga clic aquí
                    </a>
                </div>
            </div>
        </section>

        <section>
            <h2>
                <span style="font-weight: 400;">¿Qué es La Encuestadora?</span>
            </h2>
            <div>
                <p>La Encuestadora es un panel de encuestas gratuito donde puede ganar dinero haciendo encuestas. Nuestras encuestas están relacionadas con la vida cotidiana. No hay preguntas para las que no sepa la respuesta, solo opiniones. Recopilamos opiniones para ayudar a nuestros socios a comprender el panorama general.</p>

                <p>Su opinión, junto con cientos y miles de otras, envía un mensaje contundente a las empresas y organizaciones. Necesitan escuchar sus pensamientos y deseos. En La Encuestadora valoramos su opinión y contribución social, y lo recompensamos por ello.</p>
            </div>

            <p class="text-center mt-5">
                Si tiene alguna pregunta, no dude en leer nuestra página de <a href="/Home/Faqs">Preguntas frecuentes</a> aquí o contáctenos en <a href="mailto:support@laencuestadora.com">support@laencuestadora.com</a>
            </p>


        </section>
    </div>
</div>

</div>

WebApp.NET_MVC-2022-12D-PP_Encuestadora/Views/Home/Faqs.cshtml
@{
    ViewData["Title"] = "Faqs Page";
}

<div>
    
    @*<p>--------------------Seccion Faqs--------------------</p>*@
    <div class="content bg-white">
        <div class="content container-fluid">
            <section class="row">
                <div style="margin:23px 0;">
                    <div class="col-12 col-lg-6">
                        <h1>
                            Preguntas frecuentes
                        </h1>
                    </div>
                    <div class="section-text">
                        <p>
                            <em>
                                En esta página puede encontrar las preguntas y respuestas más comunes que tenían otros miembros.
                            </em>
                        </p>
                        <p>Si no puede encontrar su respuesta, contáctenos directamente en <a href="mailto:support@laencuestadora.com">support@laencuestadora.com</a>. Estamos encantados de responder a todas sus preguntas que podrían ser útiles para otros usuarios.</p>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

WebApp.NET_MVC-2022-12D-PP_Encuestadora/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    
    @*<p>--------------------Seccion Portada--------------------</p>*@
  
    <div>
        <div>
            <section class="row">
                <div class="col-12 col-lg-6">
                    <div style="margin:23px 0;">
                        <h1>
                            Encuestas pagas: gane dinero en línea
                            <br>
                        </h1>
                    </div>
                    <div class="section-text">
                        Obtenga hasta 500 puntos por cada encuesta
                    </div>
                    <div class="section-text">
                        Pago fácil y seguro
                    </div>
                </div>
            </section>
            <br />
            <section>
                <div class="section-wrap">
                    <h2>
                        Cómo ganar con encuestas pagas en 3 sencillos pasos
                        <br />
                    </h2>
                    <br />
                    <div style="display: flex;">
                        <div class="col-12 col-lg-4">
                            <img class="col-icon" alt="Registrese en La Encuestadora" src="/img/imagen1.png">
                            <h4>Regístrese</h4>
                            <p>
                                Todos pueden unirse. Es fácil de registrarse y solo toma 30 segundos.
                                <a href="/Home/Login">Inicie el registro aquí</a>
                            </p>
                        </div>
                        <div class="col-12 col-lg-4">
                            <img class="col-icon" alt="Conteste online" src="/img/imagen2.png">
                            <h4>Responder</h4>
                            <p>
                                Se le invitará por correo electrónico a las encuestas. Contesta honestamente. Sus respuestas son anónimas.
                            </p>
                        </div>
                        <div class="col-12 col-lg-4">
                            <img class="col-icon" alt="Reciba pagos por responder" src="/img/imagen3.png">
                            <h4>Recibir el pago</h4>
                            <p>
                                Cuando haya alcanzado el umbral de puntos, puede recibir el pago con un solo clic.
                            </p>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

WebApp.NET_MVC-2022-12D-PP_Encuestadora/Views/Home/LogIn.cshtml
@{
    ViewData["Title"] = "LogIn Page";
}
<div>
    @*<p>--------------------Seccion LogIn--------------------</p>*@
    Ingrese usuario
    <input type="text" />
    Ingrese contraseña
    <input type="password" />
    <input type="button" value="Entrar" class="btn btn-primary"/>
    <br />
    <p>--------------------Seccion Clientes--------------------</p>
    <input type="button" value="Registrese" asp-area="" asp-action="Create" asp-controller="Cliente" class="btn btn-primary" /> | 
    <a asp-area="" asp-controller="Cliente" asp-action="Index">Index Clientes</a>
    <p>Comentario1: Falta filtrar encuestas solo creadas por el cliente <b> REALIZADO</b></p>
    <p>Comentario2: Falta ver resultado de EncuestaRespondida del cliente <b> REALIZADO</b></p>
    <p>Comentario3: Falta solucionar error en tiempo de ejecucion creates <b> REALIZADO</b></p>
    <p>--------------------Seccion Usuarios--------------------</p>
    <input type="button" value="Registrese" asp-area="" asp-action="Create" asp-controller="Usuario" class="btn btn-primary" /> | 
    <a asp-area="" asp-controller="Usuario" asp-action="Index">Index Usuarios</a>
    <p>Comentario1: Falta ver encuestas disponibles para usuarios <b> REALIZADO</b></p>
    <p>Comentario2: Falta ver puntos acumulados por el usuario <b> REALIZADO</b></p>
    <p>Comentario3: Falta ver respuestas de EncuestaRespondida del Usuario <b> REALIZADO</b></p>
    <p>Comentario4: Falta la creacion de EncuestaRespondida con datos de Usuario y Encuesta y Sumar puntos<b> REALIZADO</b></p>
</div>